export ZSH="$HOME/.oh-my-zsh"
export PATH="/root/.local/bin:$PATH"

ZSH_THEME="robbyrussell"
zstyle ':omz:update' frequency 30
zstyle ':completion::complete:make:*:targets' call-command true
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

COMPLETION_WAITING_DOTS="true"

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
)

alias increasevol=partprobe /dev/sdb && resize2fs /dev/sdb

source $ZSH/oh-my-zsh.sh