export ZSH="$HOME/.oh-my-zsh"
export PATH="/root/.local/bin:$PATH"
export PATH="/root/.fzf/bin:$PATH"

ZSH_THEME="robbyrussell"

zstyle ':omz:update' frequency 30
zstyle ':completion::complete:make:*:targets' call-command true

COMPLETION_WAITING_DOTS="true"

plugins=(
    git
    fzf
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
)

function whois() {
	TOKEN=$(cat /root/.ipinfo.token)
	curl -s https://ipinfo.io/${1}\?token=${TOKEN} | jq '.'
}

function increasevol(disk) {
    echo "Old size : $(df -h | grep "$disk" | awk '{print $2}')
    partprobe /dev/$disk
    resize2fs /dev/$disk
    echo "New size : $(df -h | grep "$disk" | awk '{print $2}')
}

source $ZSH/oh-my-zsh.sh